export const CurrentUserStoryData = [
  {
    id: 1,
    username: 'Alan',
    title: 'Albums',
    profile:
      'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
    stories: [
      {
        id: 0,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 1,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 2,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 3,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 4,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 5,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 6,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 7,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 8,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 9,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 0,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 1,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 2,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 3,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 4,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 5,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 6,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 7,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 8,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 9,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 0,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 1,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 2,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 3,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 4,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 5,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 6,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 7,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 8,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 9,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 0,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 1,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 2,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 3,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 4,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 5,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 6,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 7,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 8,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 9,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
    ],
  },
];
