export const SingleStoryData = [
  {
    id: 1,
    username: 'Alan',
    title: 'Albums',
    profile:
      'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
    stories: [
      {
        id: 0,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 1,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 2,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 3,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 4,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 5,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 6,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 7,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 8,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 9,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 10,
        url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 11,
        url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 12,
        url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 13,
        url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
        type: 'image',
        duration: 5,
        storyId: 1,
        isSeen: false,
      },
      {
        id: 14,
        url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
        type: 'image',
        duration: 15,
        storyId: 1,
        isSeen: false,
      },
      // {
      //   id: 15,
      //   url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 16,
      //   url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 17,
      //   url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 18,
      //   url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 19,
      //   url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 20,
      //   url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 21,
      //   url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 22,
      //   url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 23,
      //   url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 24,
      //   url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 25,
      //   url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 26,
      //   url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 27,
      //   url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 28,
      //   url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 29,
      //   url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 30,
      //   url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 31,
      //   url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 32,
      //   url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 33,
      //   url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 34,
      //   url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 35,
      //   url: 'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 36,
      //   url: 'https://sosugary.com/wp-content/uploads/2022/01/TheWeeknd_001.jpg',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 37,
      //   url: 'https://images.pexels.com/photos/4668521/pexels-photo-4668521.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 38,
      //   url: 'https://images.pexels.com/photos/1595655/pexels-photo-1595655.jpeg?auto=compress&cs=tinysrgb&w=600', // story url
      //   type: 'image',
      //   duration: 5,
      //   storyId: 1,
      //   isSeen: false,
      // },
      // {
      //   id: 39,
      //   url: 'https://images.pexels.com/photos/2058498/pexels-photo-2058498.jpeg?auto=compress&cs=tinysrgb&w=600',
      //   type: 'image',
      //   duration: 15,
      //   storyId: 1,
      //   isSeen: false,
      // },
    ],
  },
];
